## import

In [4]:
import msea
# %pip install msea
from msea import SetLibrary
import numpy
import scipy
import pandas as pd
from pprint import pprint
# %pip install biom-format
from biom import load_table  # reqired for parsing BIOM formated dataset
from skbio.stats.composition import ancom
# %pip install scikit-bio

We started with loading and preparing 16S dataset, which can be downloaded from [Qiita](https://qiita.ucsd.edu/study/description/10483#):

In [2]:
# %pip install numpy
%pip install --upgrade scikit-bio

Requirement already satisfied: scikit-bio in /users/aflemis1/.local/lib/python3.11/site-packages (0.7.0)
Requirement already satisfied: requests>=2.20.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (2.32.5)
Requirement already satisfied: decorator>=3.4.2 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (5.2.1)
Requirement already satisfied: natsort>=4.0.3 in /users/aflemis1/.local/lib/python3.11/site-packages (from scikit-bio) (8.4.0)
Requirement already satisfied: numpy>=1.17.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (2.3.3)
Requirement already satisfied: pandas>=1.5.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (2.3.2)
Requirement already satisfied: scipy>=1.9.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (1.16.2)
Requirement already satisfied: h5py>=3.6.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (3.14.0)
Requirement already satisfied: biom-format>=2.1.16 in /users/aflemis1/.local/lib/python3.11/site-packages (from scikit-bio) (2.1.17)
Requirement already satisfied: statsmodels>=0.14.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (0.14.5)
Requirement already satisfied: patsy>=0.5.0 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from scikit-bio) (1.0.1)
Requirement already satisfied: array-api-compat>=1.3 in /users/aflemis1/.local/lib/python3.11/site-packages (from scikit-bio) (1.12.0)
Requirement already satisfied: click in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from biom-format>=2.1.16->scikit-bio) (8.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from pandas>=1.5.0->scikit-bio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from pandas>=1.5.0->scikit-bio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from pandas>=1.5.0->scikit-bio) (2025.2)
Requirement already satisfied: six>=1.5 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->scikit-bio) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from requests>=2.20.0->scikit-bio) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from requests>=2.20.0->scikit-bio) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from requests>=2.20.0->scikit-bio) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from requests>=2.20.0->scikit-bio) (2025.8.3)
Requirement already satisfied: packaging>=21.3 in /users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages (from statsmodels>=0.14.0->scikit-bio) (25.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
table = load_table("../csv_files/10483_45784_otu_table.biom")

print("biom table shape: ", table.shape)  # OTUs x samples
# Optionally normalize data on the sample axis -> relative abundance
# table.norm(axis='sample', inplace=True)

# Load metadata
meta_df = pd.read_csv(
    '../csv_files/10483_20230206-075026.txt',
    sep='\t',
    index_col='sample_name')
meta_df = meta_df.loc[table.ids()]


def collapse_f(id_, md):
    # collapse OTUs to genus-level
    genus_idx = 5
    return '; '.join(md['taxonomy'][:genus_idx + 1])


table_g = table.collapse(collapse_f, axis='observation')
print(table_g.shape)

# check the microbial species:
print(table_g.ids(axis='observation')[:5])
# convert to a pd.DataFrame
df_g = pd.DataFrame(
    table_g.matrix_data.toarray().T,
    columns=table_g.ids(axis='observation'),
    index=table_g.ids()
)
# Select a subset of samples from genotype 'Thy1-aSyn' for further analysis
meta_df_sub = meta_df.loc[meta_df['genotype'] == 'thy1-asyn']
df_g_sub = df_g.loc[meta_df['genotype'] == 'thy1-asyn']
print(meta_df_sub['donor_status'].value_counts())

meta_df_sub

df_g_sub

biom table shape:  (3397, 453)
(276, 453)
['k__Bacteria; p__Verrucomicrobia; c__Verrucomicrobiae; o__Verrucomicrobiales; f__Verrucomicrobiaceae; g__Akkermansia'
 'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__; g__'
 'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__'
 'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Oscillospira'
 'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Ruminococcus']
donor_status
healthy    106
pd          94
Name: count, dtype: int64

,k__Bacteria; p__Verrucomicrobia; c__Verrucomicrobiae; o__Verrucomicrobiales; f__Verrucomicrobiaceae; g__Akkermansia,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Oscillospira,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Ruminococcus,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Dorea,k__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus,k__Bacteria; p__Proteobacteria; c__Deltaproteobacteria; o__Myxococcales; f__0319-6G20; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Xanthomonadales; f__Xanthomonadaceae; g__Stenotrophomonas,...,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Robinsoniella,k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Micrococcaceae; g__Renibacterium,k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Cellulomonadaceae; g__Cellulomonas,k__Bacteria; p__Proteobacteria; c__Betaproteobacteria; o__Burkholderiales; f__Comamonadaceae; g__Leptothrix,k__Bacteria; p__Fusobacteria; c__Fusobacteriia; o__Fusobacteriales; f__Leptotrichiaceae; g__Sneathia,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__EtOH8; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__,k__Bacteria; p__Bacteroidetes; c__Flavobacteriia; o__Flavobacteriales; f__[Weeksellaceae]; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Legionellales; f__Coxiellaceae; g__Rickettsiella,k__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Rhodobacterales; f__Rhodobacteraceae; g__Rhodobacter
10483.donor1.HC,218.083333,1.512195,0.967433,0.205357,0.048780,5.405622,4.743902,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.647.ASO.PD6.D7,410.000000,0.324390,0.957854,1.035714,0.365854,2.915663,0.146341,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.386.WT.PD2.D21,741.750000,2.660976,12.260536,0.401786,0.341463,1.242972,0.073171,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.390.ASO.PD2.D21,469.000000,0.321951,5.687739,0.241071,0.256098,0.236948,0.036585,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.456.ASO.HC3.D21,246.666667,0.456098,0.639847,0.473214,0.012195,0.797189,0.390244,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10483.recip.316WT.HC1.D49,1.833333,0.043902,0.126437,0.142857,0.012195,0.046185,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.325.ASO.PD1.D49,0.000000,0.000000,0.001916,0.008929,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.467.WT.PD3.D14,0.000000,0.000000,0.000000,0.008929,0.000000,0.002008,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.560.ASO.HC4.D21,0.000000,0.000000,0.000000,0.000000,0.000000,0.002008,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10483.recip.318.ASO.HC1.D21,0.000000,0.000000,0.000000,0.000000,0.012195,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df_g_sub + 1

,k__Bacteria; p__Verrucomicrobia; c__Verrucomicrobiae; o__Verrucomicrobiales; f__Verrucomicrobiaceae; g__Akkermansia,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Oscillospira,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Ruminococcaceae; g__Ruminococcus,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Dorea,k__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus,k__Bacteria; p__Proteobacteria; c__Deltaproteobacteria; o__Myxococcales; f__0319-6G20; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Xanthomonadales; f__Xanthomonadaceae; g__Stenotrophomonas,...,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Robinsoniella,k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Micrococcaceae; g__Renibacterium,k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Cellulomonadaceae; g__Cellulomonas,k__Bacteria; p__Proteobacteria; c__Betaproteobacteria; o__Burkholderiales; f__Comamonadaceae; g__Leptothrix,k__Bacteria; p__Fusobacteria; c__Fusobacteriia; o__Fusobacteriales; f__Leptotrichiaceae; g__Sneathia,k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__EtOH8; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__,k__Bacteria; p__Bacteroidetes; c__Flavobacteriia; o__Flavobacteriales; f__[Weeksellaceae]; g__,k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Legionellales; f__Coxiellaceae; g__Rickettsiella,k__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Rhodobacterales; f__Rhodobacteraceae; g__Rhodobacter
10483.donor1.HC,219.083333,2.512195,1.967433,1.205357,1.048780,6.405622,5.743902,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.647.ASO.PD6.D7,411.000000,1.324390,1.957854,2.035714,1.365854,3.915663,1.146341,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.386.WT.PD2.D21,742.750000,3.660976,13.260536,1.401786,1.341463,2.242972,1.073171,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.390.ASO.PD2.D21,470.000000,1.321951,6.687739,1.241071,1.256098,1.236948,1.036585,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.456.ASO.HC3.D21,247.666667,1.456098,1.639847,1.473214,1.012195,1.797189,1.390244,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10483.recip.316WT.HC1.D49,2.833333,1.043902,1.126437,1.142857,1.012195,1.046185,1.000000,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.325.ASO.PD1.D49,1.000000,1.000000,1.001916,1.008929,1.000000,1.000000,1.000000,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.467.WT.PD3.D14,1.000000,1.000000,1.000000,1.008929,1.000000,1.002008,1.000000,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.560.ASO.HC4.D21,1.000000,1.000000,1.000000,1.000000,1.000000,1.002008,1.000000,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10483.recip.318.ASO.HC1.D21,1.000000,1.000000,1.000000,1.000000,1.012195,1.000000,1.000000,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

Next, we perform DA analysis using ANCOM to identify DA microbes:

In [8]:
ancom_df, percentile_df = ancom(df_g_sub + 1,  # adding pseudocounts
                                meta_df_sub['donor_status'],
                                alpha=0.1,
                                p_adjust='holm-bonferroni')

microbes_DA = ancom_df.loc[ancom_df['Signif']].index
print(microbes_DA)

# retain genus names
microbes_DA = filter(None, [s.split('; ')[-1].lstrip('g__')
                            for s in microbes_DA])
# convert to set
microbes_DA = set(microbes_DA)
print(microbes_DA)

/users/aflemis1/.conda/envs/msea/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py:611: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, axis=axis, **kwds)

Index(['k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__',
       'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Blautia',
       'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Clostridiaceae; g__',
       'k__Bacteria; p__Bacteroidetes; c__Bacteroidia; o__Bacteroidales; f__Rikenellaceae; g__',
       'k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Enterobacteriales; f__Enterobacteriaceae; g__Proteus',
       'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Eubacteriaceae; g__Pseudoramibacter_Eubacterium',
       'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Clostridium',
       'k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Veillonellaceae; g__',
       'k__Bacteria; p__Proteobacteria; c__Deltaproteobacteria; o__Desulfovibrionales; f__Desulfovibrionaceae; g__Bilophila'],
      dtype='object')
{'Pseudoramibacter_Eubacterium', 'Bilophila', 'Clostridium', 'Proteus', 'Blautia'}

In [12]:
gmt_filepath = \
    'https://bitbucket.org/wangz10/msea/raw/aee6dd184e9bde152b4d7c2f3c7245efc1b80d23/msea/data/human_genes_associated_microbes/set_library.gmt'

d_gmt = msea.read_gmt(gmt_filepath)

d_gmt

{'A2M': {'Azomonas', 'Borrelia', 'Pseudomonas', 'Salmonella', 'Sodalis'},
 'AAAS': {'Colwellia',
  'Deinococcus',
  'Idiomarina',
  'Neisseria',
  'Pseudidiomarina',
  'Pseudoalteromonas'},
 'AACS': {'Acetobacter',
  'Acinetobacter',
  'Azomonas',
  'Corynebacterium',
  'Enterobacter',
  'Klebsiella',
  'Mycobacterium',
  'Mycoplasma',
  'Pseudomonas',
  'Sodalis',
  'Staphylococcus',
  'Streptomyces',
  'Tetragenococcus'},
 'AARS': {'Agrobacterium',
  'Aquifex',
  'Archaeoglobus',
  'Bacillus',
  'Bdellovibrio',
  'Borrelia',
  'Bradyrhizobium',
  'Burkholderia',
  'Caulobacter',
  'Clostridium',
  'Cyanobacterium',
  'Enterococcus',
  'Geobacillus',
  'Ignicoccus',
  'Metallosphaera',
  'Methanocaldococcus',
  'Methanococcoides',
  'Methanococcus',
  'Methanolobus',
  'Methanopyrus',
  'Methanosaeta',
  'Methanosarcina',
  'Methanosphaera',
  'Methanothermobacter',
  'Methanothermococcus',
  'Microcystis',
  'Mycobacterium',
  'Mycoplasma',
  'Myxococcus',
  'Prochlorococcus',
  'Pseudomonas',
  'Pyrococcus',
  'Sodalis',
  'Spirochaeta',
  'Staphylococcus',
  'Streptomyces',
  'Stygiolobus',
  'Sulfolobus',
  'Synechococcus',
  'Tetragenococcus',
  'Thermosynechococcus',
  'Thermus',
  'Xanthomonas'},
 'ABCA1': {'Azomonas',
  'Bacteroides',
  'Chlamydia',
  'Citrobacter',
  'Clostridium',
  'Dorea',
  'Formosa',
  'Gordonia',
  'Lactobacillus',
  'Mycobacterium',
  'Pediococcus',
  'Porphyromonas',
  'Pseudomonas',
  'Rhodobacter',
  'Sodalis',
  'Streptomyces'},
 'ABCB1': {'Acidithiobacillus',
  'Azomonas',
  'Bacillus',
  'Dorea',
  'Formosa',
  'Haemophilus',
  'Helicobacter',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Lawsonia',
  'Mycobacterium',
  'Nannocystis',
  'Propionibacterium',
  'Pseudomonas',
  'Rhodococcus',
  'Serratia',
  'Sodalis',
  'Sorangium',
  'Staphylococcus',
  'Streptomyces',
  'Vibrio'},
 'ABCC1': {'Azomonas',
  'Bacillus',
  'Dorea',
  'Lactococcus',
  'Mycobacterium',
  'Pseudomonas',
  'Staphylococcus',
  'Streptomyces'},
 'ABCC2': {'Azomonas',
  'Bacillus',
  'Klebsiella',
  'Lactobacillus',
  'Pseudomonas',
  'Rhodococcus',
  'Saccharopolyspora',
  'Sodalis',
  'Streptomyces'},
 'ABCG1': {'Bacillus',
  'Dorea',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Mycobacterium',
  'Porphyromonas',
  'Rhodobacter'},
 'ABCG2': {'Actinomyces',
  'Arthrospira',
  'Azomonas',
  'Bacillus',
  'Clostridium',
  'Formosa',
  'Gardnerella',
  'Gordonia',
  'Helicobacter',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Mycobacterium',
  'Mycoplasma',
  'Pseudomonas',
  'Salmonella',
  'Serratia',
  'Sodalis',
  'Spirulina',
  'Streptomyces'},
 'ABL1': {'Bacillus',
  'Francisella',
  'Helicobacter',
  'Mycobacterium',
  'Salmonella',
  'Sodalis'},
 'ABR': {'Acinetobacter',
  'Anaplasma',
  'Bacillus',
  'Pediococcus',
  'Salmonella',
  'Sodalis',
  'Streptococcus',
  'Streptomyces'},
 'ACD': {'Acidovorax',
  'Azomonas',
  'Bacillus',
  'Clostridium',
  'Hydrogenophaga',
  'Lactobacillus',
  'Methanococcus',
  'Pseudomonas',
  'Variovorax'},
 'ACE': {'Acetobacter',
  'Acidovorax',
  'Acinetobacter',
  'Actinomyces',
  'Actinoplanes',
  'Agrobacterium',
  'Akkermansia',
  'Aliivibrio',
  'Arcanobacterium',
  'Arthrospira',
  'Azoarcus',
  'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Bdellovibrio',
  'Bifidobacterium',
  'Bradyrhizobium',
  'Brevundimonas',
  'Burkholderia',
  'Campylobacter',
  'Chlamydia',
  'Clostridium',
  'Comamonas',
  'Corynebacterium',
  'Coxiella',
  'Cupriavidus',
  'Cyanobacterium',
  'Deinococcus',
  'Desulfovibrio',
  'Dickeya',
  'Enterobacter',
  'Enterococcus',
  'Erwinia',
  'Fibrobacter',
  'Filifactor',
  'Formosa',
  'Fusobacterium',
  'Gemella',
  'Geobacillus',
  'Gluconobacter',
  'Gordonia',
  'Granulicatella',
  'Haemophilus',
  'Helicobacter',
  'Herbaspirillum',
  'Hydrogenophaga',
  'Hyphomicrobium',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Legionella',
  'Leptotrichia',
  'Leuconostoc',
  'Lysobacter',
  'Megasphaera',
  'Methanococcoides',
  'Methanolobus',
  'Methanosaeta',
  'Methanosarcina',
  'Methanosphaera',
  'Methanothermobacter',
  'Methylosinus',
  'Methyloversatilis',
  'Microbacterium',
  'Micrococcus',
  'Microcystis',
  'Mycobacterium',
  'Mycoplasma',
  'Neisseria',
  'Nitrobacter',
  'Nitrosospira',
  'Nitrospira',
  'Nocardia',
  'Oribacterium',
  'Parabacteroides',
  'Paracoccus',
  'Pediococcus',
  'Phascolarctobacterium',
  'Polynucleobacter',
  'Porphyromonas',
  'Prevotella',
  'Propionibacterium',
  'Providencia',
  'Pseudomonas',
  'Pyrococcus',
  'Ralstonia',
  'Rhizobium',
  'Rhodocyclus',
  'Rhodoplanes',
  'Rubrivivax',
  'Ruegeria',
  'Ruminococcus',
  'Salmonella',
  'Sarcina',
  'Skermanella',
  'Sodalis',
  'Sphingobacterium',
  'Sphingomonas',
  'Spirulina',
  'Staphylococcus',
  'Stenotrophomonas',
  'Streptococcus',
  'Streptomyces',
  'Tannerella',
  'Tetragenococcus',
  'Thauera',
  'Thermobaculum',
  'Thermus',
  'Thiobacillus',
  'Treponema',
  'Trichococcus',
  'Ureaplasma',
  'Veillonella',
  'Vibrio',
  'Virgibacillus',
  'Weissella',
  'Wolbachia',
  'Xanthomonas',
  'Yersinia',
  'Zoogloea'},
 'ACE2': {'Acinetobacter',
  'Arthrospira',
  'Bacillus',
  'Klebsiella',
  'Serratia',
  'Sodalis',
  'Spirulina',
  'Thermus',
  'Ureaplasma',
  'Xanthomonas'},
 'ACP5': {'Aggregatibacter',
  'Azomonas',
  'Enterococcus',
  'Mycoplasma',
  'Porphyromonas',
  'Pseudomonas',
  'Saccharopolyspora',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptomyces',
  'Tetragenococcus',
  'Treponema'},
 'ACPP': {'Achromobacter',
  'Acinetobacter',
  'Azomonas',
  'Klebsiella',
  'Microbacterium',
  'Pseudomonas',
  'Salmonella',
  'Sodalis'},
 'ACR': {'Acidaminococcus',
  'Azomonas',
  'Bacillus',
  'Campylobacter',
  'Erythrobacter',
  'Formosa',
  'Helicobacter',
  'Lactococcus',
  'Mycobacterium',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Sulfolobus',
  'Synechococcus',
  'Vibrio',
  'Xanthomonas',
  'Zymomonas'},
 'ACTB': {'Acinetobacter',
  'Edwardsiella',
  'Formosa',
  'Lactobacillus',
  'Myxococcus',
  'Piscirickettsia',
  'Saccharothrix',
  'Sinorhizobium',
  'Staphylococcus',
  'Streptococcus',
  'Streptomyces',
  'Ureaplasma',
  'Vibrio'},
 'ADA': {'Actinomadura',
  'Azomonas',
  'Bacillus',
  'Mycobacterium',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptomyces'},
 'ADAM10': {'Acinetobacter',
  'Anaplasma',
  'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Chlamydia',
  'Citrobacter',
  'Clostridium',
  'Formosa',
  'Gordonia',
  'Helicobacter',
  'Mycoplasma',
  'Neisseria',
  'Porphyromonas',
  'Pseudomonas',
  'Salmonella',
  'Serratia',
  'Sodalis',
  'Staphylococcus'},
 'ADAM17': {'Acinetobacter',
  'Azomonas',
  'Bacteroides',
  'Chlamydia',
  'Corynebacterium',
  'Formosa',
  'Helicobacter',
  'Lactobacillus',
  'Mycobacterium',
  'Neisseria',
  'Porphyromonas',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Streptomyces',
  'Tannerella',
  'Vibrio'},
 'ADAMTS13': {'Bacillus',
  'Burkholderia',
  'Campylobacter',
  'Clostridium',
  'Coxiella',
  'Ehrlichia',
  'Legionella',
  'Leptospira',
  'Mycoplasma',
  'Neisseria',
  'Sodalis',
  'Streptococcus'},
 'ADH4': {'Agrobacterium',
  'Bacillus',
  'Lactococcus',
  'Leuconostoc',
  'Mycoplasma',
  'Salmonella'},
 'ADH5': {'Acinetobacter',
  'Bacillus',
  'Clostridium',
  'Enterobacter',
  'Klebsiella',
  'Leuconostoc'},
 'ADIPOQ': {'Aggregatibacter',
  'Allobaculum',
  'Arthrospira',
  'Bacillus',
  'Bacteroides',
  'Bifidobacterium',
  'Chlamydia',
  'Clostridium',
  'Dorea',
  'Enterococcus',
  'Helicobacter',
  'Lactobacillus',
  'Parabacteroides',
  'Porphyromonas',
  'Prevotella',
  'Salmonella',
  'Sodalis',
  'Spirulina',
  'Thermus'},
 'ADIPOR1': {'Bacillus',
  'Clostridium',
  'Dorea',
  'Lactobacillus',
  'Staphylococcus'},
 'ADIPOR2': {'Bacillus',
  'Bacteroides',
  'Bifidobacterium',
  'Clostridium',
  'Dorea',
  'Helicobacter',
  'Lactobacillus',
  'Staphylococcus'},
 'ADK': {'Acinetobacter',
  'Aggregatibacter',
  'Agrobacterium',
  'Aliivibrio',
  'Bacillus',
  'Chlamydia',
  'Edwardsiella',
  'Enterococcus',
  'Haemophilus',
  'Leptospira',
  'Mannheimia',
  'Mycobacterium',
  'Mycoplasma',
  'Neisseria',
  'Pasteurella',
  'Salmonella',
  'Sodalis',
  'Streptococcus',
  'Streptomyces',
  'Tetragenococcus',
  'Trichococcus',
  'Vibrio',
  'Xanthomonas'},
 'ADM': {'Azomonas',
  'Bifidobacterium',
  'Lactobacillus',
  'Pseudomonas',
  'Serratia',
  'Sodalis',
  'Staphylococcus',
  'Streptomyces'},
 'ADO': {'Acinetobacter',
  'Bacillus',
  'Bifidobacterium',
  'Burkholderia',
  'Cyanobacterium',
  'Enterococcus',
  'Erythrobacter',
  'Mycobacterium',
  'Nevskia',
  'Nostoc',
  'Oscillatoria',
  'Prochlorococcus',
  'Pseudomonas',
  'Synechococcus',
  'Thermus'},
 'ADRB2': {'Formosa',
  'Halobacterium',
  'Mycobacterium',
  'Neisseria',
  'Porphyromonas',
  'Pseudomonas',
  'Rhodobacter',
  'Staphylococcus'},
 'ADSS': {'Bacillus',
  'Helicobacter',
  'Methanocaldococcus',
  'Methanococcus',
  'Prochlorococcus',
  'Pyrococcus',
  'Synechococcus'},
 'AES': {'Alicyclobacillus',
  'Azomonas',
  'Bifidobacterium',
  'Corynebacterium',
  'Pseudomonas',
  'Salmonella',
  'Staphylococcus'},
 'AFP': {'Chlamydia',
  'Formosa',
  'Gardnerella',
  'Helicobacter',
  'Mycobacterium',
  'Mycoplasma',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Treponema',
  'Ureaplasma'},
 'AGA': {'Azomonas',
  'Bacillus',
  'Colwellia',
  'Helicobacter',
  'Idiomarina',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Leuconostoc',
  'Mycobacterium',
  'Mycoplasma',
  'Pediococcus',
  'Pseudidiomarina',
  'Pseudomonas',
  'Salmonella',
  'Shewanella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Weissella'},
 'AGER': {'Acinetobacter',
  'Azomonas',
  'Lactobacillus',
  'Maricaulis',
  'Oceanicaulis',
  'Salmonella',
  'Staphylococcus'},
 'AGL': {'Acinetobacter',
  'Agrobacterium',
  'Bacillus',
  'Cupriavidus',
  'Cytophaga',
  'Enterococcus',
  'Flavobacterium',
  'Flexibacter',
  'Halobacterium',
  'Haloferax',
  'Klebsiella',
  'Methanococcus',
  'Methanothermococcus',
  'Mycobacterium',
  'Myxococcus',
  'Neisseria',
  'Paenibacillus',
  'Proteus',
  'Pseudomonas',
  'Ralstonia',
  'Rhizobium',
  'Saccharopolyspora',
  'Sinorhizobium',
  'Sodalis',
  'Streptococcus',
  'Streptomyces',
  'Thermus'},
 'AGO2': {'Archaeoglobus',
  'Chlamydia',
  'Methanocaldococcus',
  'Thermus',
  'Wolbachia'},
 'AGPS': {'Aerococcus',
  'Agrobacterium',
  'Atopobium',
  'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Bifidobacterium',
  'Bilophila',
  'Brachyspira',
  'Campylobacter',
  'Citrobacter',
  'Clostridium',
  'Corynebacterium',
  'Desulfovibrio',
  'Enterococcus',
  'Eubacterium',
  'Faecalibacterium',
  'Francisella',
  'Gordonia',
  'Helicobacter',
  'Lactobacillus',
  'Leuconostoc',
  'Mycoplasma',
  'Pediococcus',
  'Porphyromonas',
  'Prevotella',
  'Propionibacterium',
  'Pseudomonas',
  'Rhizobium',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptomyces',
  'Tetragenococcus',
  'Turicibacter',
  'Veillonella',
  'Weissella'},
 'AGRP': {'Bifidobacterium',
  'Colwellia',
  'Gordonia',
  'Idiomarina',
  'Pseudidiomarina',
  'Pseudoalteromonas'},
 'AHCY': {'Cupriavidus',
  'Desulfovibrio',
  'Ralstonia',
  'Saccharomonospora',
  'Sinorhizobium'},
 'AICDA': {'Bacteroides',
  'Borrelia',
  'Helicobacter',
  'Lactobacillus',
  'Mycoplasma',
  'Sodalis',
  'Streptococcus'},
 'AIF1': {'Gordonia',
  'Haloferax',
  'Lactobacillus',
  'Metallosphaera',
  'Pyrococcus',
  'Rhodobacter',
  'Rickettsia',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Stygiolobus',
  'Sulfolobus'},
 'AIM2': {'Actinomyces',
  'Aggregatibacter',
  'Azomonas',
  'Bacillus',
  'Burkholderia',
  'Campylobacter',
  'Chlamydia',
  'Citrobacter',
  'Enterococcus',
  'Formosa',
  'Francisella',
  'Fusobacterium',
  'Haemophilus',
  'Helicobacter',
  'Klebsiella',
  'Legionella',
  'Mycobacterium',
  'Neisseria',
  'Porphyromonas',
  'Prevotella',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Treponema'},
 'AK1': {'Azomonas',
  'Bacillus',
  'Brevibacillus',
  'Clostridium',
  'Enterococcus',
  'Klebsiella',
  'Lysinibacillus',
  'Mycobacterium',
  'Photobacterium',
  'Proteus',
  'Pseudomonas',
  'Rhizobium',
  'Rhodococcus',
  'Sodalis',
  'Staphylococcus',
  'Thiobacillus'},
 'AK7': {'Arthrobacter',
  'Fulvivirga',
  'Lactobacillus',
  'Methanoculleus',
  'Methanofollis',
  'Methanogenium',
  'Methanoplanus',
  'Tetragenococcus'},
 'AKT1': {'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Campylobacter',
  'Chlamydia',
  'Clostridium',
  'Formosa',
  'Francisella',
  'Gordonia',
  'Haemophilus',
  'Helicobacter',
  'Klebsiella',
  'Lactobacillus',
  'Mycobacterium',
  'Mycoplasma',
  'Pasteurella',
  'Porphyromonas',
  'Proteus',
  'Pseudomonas',
  'Salmonella',
  'Serratia',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Streptomyces'},
 'AKT2': {'Azomonas', 'Formosa', 'Lactobacillus', 'Proteus', 'Pseudomonas'},
 'ALAD': {'Agrobacterium',
  'Azomonas',
  'Bradyrhizobium',
  'Burkholderia',
  'Chlorobium',
  'Citrobacter',
  'Corynebacterium',
  'Geobacillus',
  'Gordonia',
  'Haloarcula',
  'Lactobacillus',
  'Lysinibacillus',
  'Pseudomonas',
  'Pyrobaculum',
  'Rhizobium',
  'Rhodobacter',
  'Rhodothermus',
  'Sodalis',
  'Thermus',
  'Wolbachia'},
 'ALB': {'Acinetobacter',
  'Actinomyces',
  'Azomonas',
  'Bacillus',
  'Bifidobacterium',
  'Borrelia',
  'Cellulosimicrobium',
  'Clostridium',
  'Enterococcus',
  'Formosa',
  'Helicobacter',
  'Klebsiella',
  'Lactobacillus',
  'Mycobacterium',
  'Porphyromonas',
  'Prevotella',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Streptococcus',
  'Tetragenococcus'},
 'ALDH2': {'Archaeoglobus',
  'Azomonas',
  'Bacillus',
  'Fusobacterium',
  'Helicobacter',
  'Magnetospirillum',
  'Mycobacterium',
  'Natronomonas',
  'Prevotella',
  'Pseudomonas',
  'Sodalis',
  'Staphylococcus'},
 'ALK': {'Acidisphaera',
  'Acinetobacter',
  'Alcanivorax',
  'Alkalibacterium',
  'Arthrospira',
  'Azomonas',
  'Bacillus',
  'Borrelia',
  'Citrobacter',
  'Clostridium',
  'Desulfovibrio',
  'Dietzia',
  'Enterococcus',
  'Facklamia',
  'Formosa',
  'Fusobacterium',
  'Gordonia',
  'Helicobacter',
  'Lactobacillus',
  'Legionella',
  'Leuconostoc',
  'Mannheimia',
  'Marinilactibacillus',
  'Methanosarcina',
  'Mycobacterium',
  'Mycoplasma',
  'Nocardioides',
  'Nostoc',
  'Prauserella',
  'Prochlorococcus',
  'Proteus',
  'Pseudomonas',
  'Pseudonocardia',
  'Rhodococcus',
  'Salmonella',
  'Sodalis',
  'Spirulina',
  'Staphylococcus',
  'Streptococcus',
  'Streptomyces',
  'Synechococcus',
  'Terrimonas',
  'Treponema',
  'Yersinia'},
 'ALOX15': {'Azomonas',
  'Lactococcus',
  'Mycobacterium',
  'Pseudomonas',
  'Rickettsiella',
  'Salmonella'},
 'ALOX5': {'Achromobacter',
  'Actinobacillus',
  'Aggregatibacter',
  'Borrelia',
  'Enterococcus',
  'Formosa',
  'Francisella',
  'Helicobacter',
  'Mycobacterium',
  'Mycoplasma',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Tetragenococcus'},
 'ALPK1': {'Burkholderia',
  'Formosa',
  'Helicobacter',
  'Neisseria',
  'Salmonella'},
 'ALPP': {'Bacillus',
  'Caulobacter',
  'Chromobacterium',
  'Colwellia',
  'Idiomarina',
  'Lactococcus',
  'Marinomonas',
  'Phaeobacter',
  'Pseudidiomarina',
  'Pseudoalteromonas',
  'Pseudomonas',
  'Rheinheimera',
  'Vibrio'},
 'AMH': {'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Chlamydia',
  'Enterococcus',
  'Gardnerella',
  'Mesorhizobium',
  'Mycobacterium',
  'Mycoplasma',
  'Nautilia',
  'Nitratireductor',
  'Photobacterium',
  'Phyllobacterium',
  'Pseudomonas',
  'Tetragenococcus'},
 'AMT': {'Archaeoglobus',
  'Cyanobacterium',
  'Eubacterium',
  'Staphylococcus',
  'Synechococcus',
  'Thermus'},
 'ANGPTL4': {'Akkermansia',
  'Atopobium',
  'Bacteroides',
  'Bifidobacterium',
  'Clostridium',
  'Enterococcus',
  'Faecalibacterium',
  'Formosa',
  'Lactobacillus',
  'Prevotella',
  'Tetragenococcus'},
 'ANKH': {'Bacillus',
  'Legionella',
  'Micrococcus',
  'Rickettsia',
  'Streptomyces',
  'Yersinia'},
 'ANXA1': {'Arcanobacterium',
  'Formosa',
  'Helicobacter',
  'Mycobacterium',
  'Porphyromonas',
  'Salmonella',
  'Trueperella'},
 'ANXA2': {'Anaplasma',
  'Arcanobacterium',
  'Azomonas',
  'Borrelia',
  'Edwardsiella',
  'Formosa',
  'Helicobacter',
  'Klebsiella',
  'Mannheimia',
  'Mycoplasma',
  'Porphyromonas',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Treponema',
  'Trueperella',
  'Ureaplasma'},
 'AOX1': {'Acetobacter',
  'Achromobacter',
  'Arthrobacter',
  'Azomonas',
  'Bacillus',
  'Burkholderia',
  'Citrobacter',
  'Enterococcus',
  'Erythrobacter',
  'Geobacillus',
  'Gluconacetobacter',
  'Helicobacter',
  'Lactobacillus',
  'Lactococcus',
  'Methylobacillus',
  'Methylobacterium',
  'Micrococcus',
  'Pediococcus',
  'Pseudomonas',
  'Pyrococcus',
  'Rhodobacter',
  'Rhodothermus',
  'Roseomonas',
  'Salmonella',
  'Selenomonas',
  'Sodalis',
  'Sphingopyxis',
  'Streptococcus',
  'Streptomyces',
  'Tetragenococcus',
  'Thalassomonas',
  'Thermotoga',
  'Vitreoscilla',
  'Xanthomonas',
  'Zymomonas'},
 'APAF1': {'Arthrospira',
  'Azomonas',
  'Bacillus',
  'Chlamydia',
  'Cyanobacterium',
  'Edwardsiella',
  'Filifactor',
  'Klebsiella',
  'Mycoplasma',
  'Peptostreptococcus',
  'Porphyromonas',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Spirulina',
  'Streptomyces'},
 'APEX1': {'Bacillus',
  'Campylobacter',
  'Formosa',
  'Helicobacter',
  'Methanolobus',
  'Methanosaeta',
  'Methanosarcina',
  'Pasteurella',
  'Salmonella',
  'Serratia',
  'Sodalis',
  'Streptococcus',
  'Thermotoga'},
 'APOA1': {'Actinobacillus',
  'Aggregatibacter',
  'Akkermansia',
  'Borrelia',
  'Chlamydia',
  'Citrobacter',
  'Formosa',
  'Fusobacterium',
  'Helicobacter',
  'Klebsiella',
  'Lachnospira',
  'Lactobacillus',
  'Micrococcus',
  'Mycoplasma',
  'Oscillospira',
  'Parabacteroides',
  'Phascolarctobacterium',
  'Porphyromonas',
  'Prevotella',
  'Ruminococcus',
  'Salmonella',
  'Sodalis',
  'Streptococcus',
  'Treponema'},
 'APOA4': {'Gordonia',
  'Lachnospira',
  'Oscillospira',
  'Parabacteroides',
  'Phascolarctobacterium',
  'Ruminococcus'},
 'APOA5': {'Akkermansia',
  'Bifidobacterium',
  'Formosa',
  'Lactobacillus',
  'Methanosphaera',
  'Methanothermobacter',
  'Odoribacter',
  'Sutterella'},
 'APOB': {'Akkermansia',
  'Azomonas',
  'Bacillus',
  'Borrelia',
  'Chlamydia',
  'Dorea',
  'Edwardsiella',
  'Enterobacter',
  'Flavobacterium',
  'Formosa',
  'Fusobacterium',
  'Gordonia',
  'Helicobacter',
  'Lactobacillus',
  'Leptospira',
  'Micrococcus',
  'Mycobacterium',
  'Porphyromonas',
  'Providencia',
  'Pseudomonas',
  'Salmonella',
  'Sodalis',
  'Staphylococcus',
  'Streptococcus',
  'Treponema',
  'Vibrio'},
 'APOBEC1': {'Bacillus',
  'Klebsiella',
  'Pseudomonas',
  'Sodalis',
  'Xanthomonas'},
 'APOE': {'Acidovorax',
  'Acinetobacter',
  'Actinobacillus',
  'Actinomyces',
  'Aggregatibacter',
  'Akkermansia',
  'Anaeroplasma',
  'Anaplasma',
  'Arthrospira',
  'Azomonas',
  'Bacillus',
  'Bacteroides',
  'Bifidobacterium',
  'Borrelia',
  'Chlamydia',
  'Citrobacter',
  'Clostridium',
  'Coprobacillus',
  'Coprococcus',
  'Dorea',
  'Edwardsiella',
  'Faecalibacterium',
  'Flavobacterium',
  'Formosa',
  'Fusobacterium',
  'Gordonia',
  'Haemophilus',
  'Helicobacter',
  'Hydrogenophaga',
  'Klebsiella',
  'Lactobacillus',
  'Lactococcus',
  'Legionella',
  'Leptospira',
  'Micrococcus',
  'Mycobacterium',
  'Mycoplasma',
  'Neisseria',
  'Nostoc',
  'Oscillospira',
  'Parabacteroides',
  'Pediococcus',
  'Porphyromonas',
  'Propionibacterium',
  'Providencia',
  'Pseudomonas',
  'Rhodobacter',
  'Roseburia',
  'Ruminococcus',
  'Salmonella',
  'Sodalis',
  'Spirulina',
  'Staphylococcus',
  'Streptococcus',
  'Treponema'},
 'APP': {'Acinetobacter',
  'Actinobacillus',